### ISSUE TITLE
What is the screen resolution of the iPhone 5, 6, 6+. and iPad Air 2?

### ISSUE THREAD

**Issue by MosheBerman** [CameronBanga/iOS-Developer-and-Designer-Interview-Questions#11]
This question actually runs counter to the iOS design philosophy. We're encouraged to think in terms of size classes, not pixels or points.

**Comment by CameronBanga** [comment]
This is a good point, however going to close for now.

Given the past year or two with size classes, this resolution question is probably less valuable. But it still is a metric which even given size classes, I believe is an important bit of knowledge that a designer especially should be aware of. The pixel differences between devices can very important to know in general when designing visual elements in Photoshop, Sketch, etc. So it's still somewhat useful knowledge, and I would expect any designer I hired to at least have general understanding of the screen resolutions of these devices.

Could be clarified and some size class questions should be added for sure though.
