### ISSUE TITLE
Inter app audio issue on iOS 10

### ISSUE THREAD

**Issue by Mudasir441** [CameronBanga/iOS-Developer-and-Designer-Interview-Questions#12]
Hello. I have created a project in xcode 7.3 and used to run it on ipad having ios version 9.3.5. Now i upgraded my both xcode and ipad ios version. Inter app music is not playing on ipad now, while it plays on ipad having ios 9.3.5.

Thank you

**Comment by CameronBanga** [comment]
@Mudasir441 This isn't really a repository for help or general questions, can't really help here. I'd suggest trying StackOverflow?
