### ISSUE TITLE
Uhhhh...

### ISSUE THREAD

**Issue by bartcone** [CameronBanga/iOS-Developer-and-Designer-Interview-Questions#5]
I'm sorry, but some of these interview questions are really bad and would most likely prevent a "good" iOS dev from joining a company if they were asked these. Not meaning to be rude, but this could cost a company a good hire :p

**Comment by CameronBanga** [comment]
Would be happy to take PRs or suggestions on how to make questions that would be better. Feel free to send over a suggestion and I'd be happy to ask.

This isn't meant to be an ultimate question list, but ideas on topics for an interviewer to touch upon when looking at prospective hired.
